### PR TITLE
allow SS5

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Comment by jonom** [comment]
Thanks @xini, I take it you've tried this on SS5 and no issues?

**Comment by xini** [comment]
Yes, it works on SS5.

**Comment by xini** [comment]
bump

**Comment by michalkleiner** [comment]
bumpity bump :)

**Comment by xini** [comment]
Thank you very much. Can you please tag this as a new version?

**Comment by jonom** [comment]
I sure will, just ran out of time before I ran out the door this morning.

**Comment by xini** [comment]
No worries 😉

**Comment by jonom** [comment]
Fixed a couple of other bugs and tagged 2.0.3. Thanks for your patience.

**Pull request merged**
